version: '3.8'

services:
  addy-mailcow-bridge:
    image: frcharron/addy-mailcow-bridge:latest  # Pulls from Docker Hub
    volumes:
      - ./lookup:/app/lookup
    networks:
      - mailcow-network # Using same network (mailcow-network) for the bridge and the mail project improve speed of the request and security (no need to expose port 6510).
    environment:
      - MAILCOW_DOMAIN==http://mailcowdockerized-nginx-mailcow-1:8080  
      - MAILCOW_API_KEY=000000-000000-000000-000000-000000 # Provided by Mailcow UI (API section)
    restart: unless-stopped  # Restart on failure (good for production)
